"""add daily_prompt_limit to users

Revision ID: 1ab190c811b5
Revises: 9927490b88de
Create Date: 2026-06-27 21:10:20.606402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab190c811b5'
down_revision: Union[str, Sequence[str], None] = '9927490b88de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_prompt_limit', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_prompt_limit')
    # ### end Alembic commands ###
