from enum import Enum


class IntentType(str, Enum):
    ORDER_STATUS = "ORDER_STATUS"
    MONTHLY_AGGREGATION = "MONTHLY_AGGREGATION"
    DATE_RANGE_AGGREGATION = "DATE_RANGE_AGGREGATION"
    PENDING_ORDERS = "PENDING_ORDERS"
    REVENUE_SUMMARY = "REVENUE_SUMMARY"
    UNKNOWN = "UNKNOWN"
